
MapSeven:
  Neos:
    FormBundle:
      elasticSearch:
        indexName: formdata
        defaultMapping:
          _all:
            analyzer: nGram_analyzer
            search_analyzer: whitespace_analyzer
          properties:
            _date:
              type: date
              index: 'no'
        transform:
          _date:
            type: Date
            options:
              format: c
Flowpack:
  ElasticSearch:
    indexes:
      default:
        formdata:
          analysis:
            filter:
              nGram_filter:
                type: nGram
                min_gram: 2
                max_gram: 20
                token_chars:
                  - letter
                  - digit
                  - punctuation
                  - symbol
            analyzer:
              nGram_analyzer:
                type: custom
                tokenizer: whitespace
                filter:
                  - lowercase
                  - asciifolding
                  - nGram_filter
              whitespace_analyzer:
                type: custom
                tokenizer: whitespace
                filter:
                  - lowercase
                  - asciifolding
              string_lowercase:
                type: custom
                tokenizer: keyword
                filter: lowercase
Neos:
  Form:
    presets:
      default:
        finisherPresets:
          'MapSeven.Neos.FormBundle:Persistence':
            implementationClassName: MapSeven\Neos\FormBundle\Finishers\PersistenceFinisher
            options: {  }
TYPO3:
  Form:
    presets:
      default:
        finisherPresets:
          'MapSeven.Neos.FormBundle:Persistence':
            implementationClassName: MapSeven\Neos\FormBundle\Finishers\PersistenceFinisher
            options: {  }
